#!/usr/bin/env bash


# Import Current Theme
DIR="$HOME/.config/qtile"
RASI="$DIR/theme/rofi/askpass.rasi"

# Rofi text dialog to get password
rofi -dmenu \
     -password \
     -i \
     -p "Root" \
     -theme ${RASI}
